// Objective-C API for talking to ll1024.com/algorithm_golang/algorithm Go package.
//   gobind -lang=objc ll1024.com/algorithm_golang/algorithm
//
// File is generated by gobind. Do not edit.

#ifndef __Algorithm_H__
#define __Algorithm_H__

@import Foundation;
#include "Universe.objc.h"


@class AlgorithmBloodGlucose;
@class AlgorithmCGMalgorithm;

@interface AlgorithmBloodGlucose : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (double)bgo;
- (void)setBGO:(double)v;
- (double)bg;
- (void)setBG:(double)v;
@end

@interface AlgorithmCGMalgorithm : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (void)addRef:(double)bloodGlucose date:(int64_t)date;
- (AlgorithmBloodGlucose*)calcBloodGlucose:(double)current date:(int64_t)date;
@end

FOUNDATION_EXPORT AlgorithmCGMalgorithm* AlgorithmNewCGMalgorithm(NSString* key);

#endif
