
// Objective-C API for talking to the following Go packages
//
//	ll1024.com/algorithm_golang/algorithm
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Algorithm_FRAMEWORK_H__
#define __Algorithm_FRAMEWORK_H__

#include "Algorithm.objc.h"
#include "Universe.objc.h"

#endif
